### ISSUE TITLE
Transient test failure

### ISSUE THREAD

**Issue by quoll** [threatgrid/ctia#306] opened 2016-05-20 17:42 UTC
During generative tests we've seen a transient failure on the test-helpers.core/encode function. We've run the test manually, and have been unable to reproduce. Stack trace and failure record below:

``` clojure
{:result #error {
 :cause "Assert failed: (string? s)"
 :via
 [{:type java.lang.AssertionError
   :message "Assert failed: (string? s)"
   :at [ctia.test_helpers.core$encode invoke "core.clj" 284]}]
 :trace
 [[ctia.test_helpers.core$encode invoke "core.clj" 284]
  [ctia.http.generative.specs$fn__8676 invoke "specs.clj" 85]
  [clojure.lang.AFn applyToHelper "AFn.java" 154]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invoke "core.clj" 630]
  [clojure.test.check.properties$apply_gen$fn__1882$fn__1883 invoke "properties.cljc" 16]
  [clojure.test.check.properties$apply_gen$fn__1882 invoke "properties.cljc" 16]
  [clojure.test.check.rose_tree$fmap invoke "rose_tree.cljc" 78]
  [clojure.test.check.generators$fmap$fn__625 invoke "generators.cljc" 89]
  [clojure.test.check.generators$gen_fmap$fn__603 invoke "generators.cljc" 55]
  [clojure.test.check.generators$call_gen invoke "generators.cljc" 41]
  [clojure.test.check$quick_check doInvoke "check.cljc" 62]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invoke "core.clj" 634]
  [ctia.http.generative.es_store_spec$spec_feedback_routes_es_store doInvoke "es_store_spec.clj" 26]
  [clojure.lang.RestFn applyTo "RestFn.java" 139]
  [clojure.core$apply invoke "core.clj" 632]
  [ctia.http.generative.es_store_spec$spec_feedback_routes_es_store invoke "es_store_spec.clj" 26]
  [ctia.http.generative.es_store_spec$fn__8567 invoke "es_store_spec.clj" 26]
  [clojure.test$test_var$fn__7670 invoke "test.clj" 704]
  [clojure.test$test_var invoke "test.clj" 704]
  [clojure.test$test_vars$fn__7692$fn__7697 invoke "test.clj" 722]
  [clojure.test$default_fixture invoke "test.clj" 674]
  [clojure.test$test_vars$fn__7692 invoke "test.clj" 722]
  [ctia.test_helpers.core$fixture_allow_all_auth invoke "core.clj" 161]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [ctia.test_helpers.core$fixture_ctia$fn__12731 invoke "core.clj" 143]
  [ctia.test_helpers.core$with_properties_ invoke "core.clj" 57]
  [ctia.test_helpers.core$fixture_ctia invoke "core.clj" 137]
  [ctia.test_helpers.core$fixture_ctia invoke "core.clj" 130]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [ctia.test_helpers.es$fixture_properties_COLON_es_store$fn__8204 invoke "es.clj" 56]
  [ctia.test_helpers.core$with_properties_ invoke "core.clj" 57]
  [ctia.test_helpers.es$fixture_properties_COLON_es_store invoke "es.clj" 41]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [ctia.test_helpers.core$fixture_properties_COLON_clean$fn__7591 invoke "core.clj" 80]
  [ctia.test_helpers.core$with_properties_ invoke "core.clj" 57]
  [ctia.test_helpers.core$fixture_properties_COLON_clean invoke "core.clj" 72]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [ctia.test_helpers.core$fixture_schema_validation invoke "core.clj" 155]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [clojure.test$default_fixture invoke "test.clj" 674]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [clojure.test$default_fixture invoke "test.clj" 674]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$test_vars invoke "test.clj" 718]
  [clojure.test$test_all_vars invoke "test.clj" 728]
  [clojure.test$test_ns invoke "test.clj" 747]
  [clojure.core$map$fn__4553 invoke "core.clj" 2624]
  [clojure.lang.LazySeq sval "LazySeq.java" 40]
  [clojure.lang.LazySeq seq "LazySeq.java" 49]
  [clojure.lang.Cons next "Cons.java" 39]
  [clojure.lang.RT next "RT.java" 674]
  [clojure.core$next__4112 invoke "core.clj" 64]
  [clojure.core$reduce1 invoke "core.clj" 909]
  [clojure.core$reduce1 invoke "core.clj" 900]
  [clojure.core$merge_with doInvoke "core.clj" 2936]
  [clojure.lang.RestFn applyTo "RestFn.java" 139]
  [clojure.core$apply invoke "core.clj" 632]
  [clojure.test$run_tests doInvoke "test.clj" 762]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invoke "core.clj" 630]
  [user$eval85$fn__150$fn__183 invoke "form-init1784935336480577525.clj" 1]
  [user$eval85$fn__150$fn__151 invoke "form-init1784935336480577525.clj" 1]
  [user$eval85$fn__150 invoke "form-init1784935336480577525.clj" 1]
  [user$eval85 invoke "form-init1784935336480577525.clj" 1]
  [clojure.lang.Compiler eval "Compiler.java" 6782]
  [clojure.lang.Compiler eval "Compiler.java" 6772]
  [clojure.lang.Compiler load "Compiler.java" 7227]
  [clojure.lang.Compiler loadFile "Compiler.java" 7165]
  [clojure.main$load_script invoke "main.clj" 275]
  [clojure.main$init_opt invoke "main.clj" 280]
  [clojure.main$initialize invoke "main.clj" 308]
  [clojure.main$null_opt invoke "main.clj" 343]
  [clojure.main$main doInvoke "main.clj" 421]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [clojure.lang.Var invoke "Var.java" 383]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.Var applyTo "Var.java" 700]
  [clojure.main main "main.java" 37]]}, :seed 1463758615722, :failing-size 0, :num-tests 1, :fail [{:id "feedback--", :entity_id "judgement-648d159e-56c4-46bc-91d2-23a2451f2f0e", :feedback -1, :reason "S *]D$8", :tlp "white"}], :shrunk {:total-nodes-visited 7, :depth 6, :result #error {
 :cause "Assert failed: (string? s)"
 :via
 [{:type java.lang.AssertionError
   :message "Assert failed: (string? s)"
   :at [ctia.test_helpers.core$encode invoke "core.clj" 284]}]
 :trace
 [[ctia.test_helpers.core$encode invoke "core.clj" 284]
  [ctia.http.generative.specs$fn__8676 invoke "specs.clj" 85]
  [clojure.lang.AFn applyToHelper "AFn.java" 154]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invoke "core.clj" 630]
  [clojure.test.check.properties$apply_gen$fn__1882$fn__1883 invoke "properties.cljc" 16]
  [clojure.test.check.properties$apply_gen$fn__1882 invoke "properties.cljc" 16]
  [clojure.test.check.rose_tree$fmap invoke "rose_tree.cljc" 78]
  [clojure.test.check.rose_tree$fmap$fn__513 invoke "rose_tree.cljc" 78]
  [clojure.core$map$fn__4553 invoke "core.clj" 2624]
  [clojure.lang.LazySeq sval "LazySeq.java" 40]
  [clojure.lang.LazySeq seq "LazySeq.java" 49]
  [clojure.lang.RT seq "RT.java" 507]
  [clojure.core$seq__4128 invoke "core.clj" 137]
  [clojure.test.check$shrink_loop invoke "check.cljc" 108]
  [clojure.test.check$failure invoke "check.cljc" 125]
  [clojure.test.check$quick_check doInvoke "check.cljc" 70]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invoke "core.clj" 634]
  [ctia.http.generative.es_store_spec$spec_feedback_routes_es_store doInvoke "es_store_spec.clj" 26]
  [clojure.lang.RestFn applyTo "RestFn.java" 139]
  [clojure.core$apply invoke "core.clj" 632]
  [ctia.http.generative.es_store_spec$spec_feedback_routes_es_store invoke "es_store_spec.clj" 26]
  [ctia.http.generative.es_store_spec$fn__8567 invoke "es_store_spec.clj" 26]
  [clojure.test$test_var$fn__7670 invoke "test.clj" 704]
  [clojure.test$test_var invoke "test.clj" 704]
  [clojure.test$test_vars$fn__7692$fn__7697 invoke "test.clj" 722]
  [clojure.test$default_fixture invoke "test.clj" 674]
  [clojure.test$test_vars$fn__7692 invoke "test.clj" 722]
  [ctia.test_helpers.core$fixture_allow_all_auth invoke "core.clj" 161]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [ctia.test_helpers.core$fixture_ctia$fn__12731 invoke "core.clj" 143]
  [ctia.test_helpers.core$with_properties_ invoke "core.clj" 57]
  [ctia.test_helpers.core$fixture_ctia invoke "core.clj" 137]
  [ctia.test_helpers.core$fixture_ctia invoke "core.clj" 130]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [ctia.test_helpers.es$fixture_properties_COLON_es_store$fn__8204 invoke "es.clj" 56]
  [ctia.test_helpers.core$with_properties_ invoke "core.clj" 57]
  [ctia.test_helpers.es$fixture_properties_COLON_es_store invoke "es.clj" 41]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [ctia.test_helpers.core$fixture_properties_COLON_clean$fn__7591 invoke "core.clj" 80]
  [ctia.test_helpers.core$with_properties_ invoke "core.clj" 57]
  [ctia.test_helpers.core$fixture_properties_COLON_clean invoke "core.clj" 72]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [ctia.test_helpers.core$fixture_schema_validation invoke "core.clj" 155]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [clojure.test$default_fixture invoke "test.clj" 674]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [clojure.test$default_fixture invoke "test.clj" 674]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$test_vars invoke "test.clj" 718]
  [clojure.test$test_all_vars invoke "test.clj" 728]
  [clojure.test$test_ns invoke "test.clj" 747]
  [clojure.core$map$fn__4553 invoke "core.clj" 2624]
  [clojure.lang.LazySeq sval "LazySeq.java" 40]
  [clojure.lang.LazySeq seq "LazySeq.java" 49]
  [clojure.lang.Cons next "Cons.java" 39]
  [clojure.lang.RT next "RT.java" 674]
  [clojure.core$next__4112 invoke "core.clj" 64]
  [clojure.core$reduce1 invoke "core.clj" 909]
  [clojure.core$reduce1 invoke "core.clj" 900]
  [clojure.core$merge_with doInvoke "core.clj" 2936]
  [clojure.lang.RestFn applyTo "RestFn.java" 139]
  [clojure.core$apply invoke "core.clj" 632]
  [clojure.test$run_tests doInvoke "test.clj" 762]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invoke "core.clj" 630]
  [user$eval85$fn__150$fn__183 invoke "form-init1784935336480577525.clj" 1]
  [user$eval85$fn__150$fn__151 invoke "form-init1784935336480577525.clj" 1]
  [user$eval85$fn__150 invoke "form-init1784935336480577525.clj" 1]
  [user$eval85 invoke "form-init1784935336480577525.clj" 1]
  [clojure.lang.Compiler eval "Compiler.java" 6782]
  [clojure.lang.Compiler eval "Compiler.java" 6772]
  [clojure.lang.Compiler load "Compiler.java" 7227]
  [clojure.lang.Compiler loadFile "Compiler.java" 7165]
  [clojure.main$load_script invoke "main.clj" 275]
  [clojure.main$init_opt invoke "main.clj" 280]
  [clojure.main$initialize invoke "main.clj" 308]
  [clojure.main$null_opt invoke "main.clj" 343]
  [clojure.main$main doInvoke "main.clj" 421]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [clojure.lang.Var invoke "Var.java" 383]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.Var applyTo "Var.java" 700]
  [clojure.main main "main.java" 37]]}, :smallest [{:id "feedback-!", :entity_id "judgement-!", :feedback 0, :reason "", :tlp "red"}]}, :test-var "spec-feedback-routes-se-store"}
```

**Comment by polygloton** [comment] 2016-05-20 17:54
I've seen this a couple of times as well.

**Comment by polygloton** [comment] 2016-05-20 17:55
I can at least improve it by writing a better assertion (so that it captures the input in the message).

**Comment by polygloton** [comment] 2016-05-20 18:10
I think [this was same bug](https://github.com/threatgrid/ctia/pull/295/commits/39144f68e1d8d25f49ca0c1b7ae903311954a9d8).

**Comment by gbuisson** [comment] 2016-05-26 11:26
I saw that issue too, I think the problem arises with the ID generator, on `ctia.test-helpers.generators.id`.

this code sometime generates empty ids and when passed to `encode`throws.

```clojure
(def gen-user-defined-short-id
  (gen/such-that (comp seq str/trim)
                 gen/string-ascii))

(def gen-uuid-short-id
  (gen/fmap (fn [[type uuid]]
              (str type "-" uuid))
            (gen/tuple
             gen-type
             gen/uuid)))

(defn gen-short-id-of-type [type]
  (gen/fmap (fn [short-id-suffix]
              (str (name type) "-" short-id-suffix))
            (gen/one-of
             [gen-user-defined-short-id
              gen/uuid])))
```

**Comment by polygloton** [comment] 2016-05-26 17:58
Its weird though, because we tried to reproduce the error with the failing example printed by the test in a REPL, and it worked fine.  Hopefully the better assertion error messages will capture it more correctly.

**Comment by polygloton** [comment] 2016-05-27 15:52
Here is another failure that is probably this bug.

```clojure
{:result #error {
 :cause "Assert failed: Assert Failed: null of type null must be a string\n(string? s)"
 :via
 [{:type java.lang.AssertionError
   :message "Assert failed: Assert Failed: null of type null must be a string\n(string? s)"
   :at [ctia.test_helpers.core$encode invoke "core.clj" 289]}]
 :trace
 [[ctia.test_helpers.core$encode invoke "core.clj" 289]
  [ctia.http.generative.specs$fn__3322 invoke "specs.clj" 86]
  [clojure.lang.AFn applyToHelper "AFn.java" 154]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invoke "core.clj" 630]
  [clojure.test.check.properties$apply_gen$fn__1761$fn__1762 invoke "properties.cljc" 16]
  [clojure.test.check.properties$apply_gen$fn__1761 invoke "properties.cljc" 16]
  [clojure.test.check.rose_tree$fmap invoke "rose_tree.cljc" 78]
  [clojure.test.check.generators$fmap$fn__491 invoke "generators.cljc" 89]
  [clojure.test.check.generators$gen_fmap$fn__469 invoke "generators.cljc" 55]
  [clojure.test.check.generators$call_gen invoke "generators.cljc" 41]
  [clojure.test.check$quick_check doInvoke "check.cljc" 62]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invoke "core.clj" 634]
  [ctia.http.generative.sql_store_spec$spec_judgement_routes_sql_store doInvoke "sql_store_spec.clj" 15]
  [clojure.lang.RestFn applyTo "RestFn.java" 139]
  [clojure.core$apply invoke "core.clj" 632]
  [ctia.http.generative.sql_store_spec$spec_judgement_routes_sql_store invoke "sql_store_spec.clj" 15]
  [ctia.http.generative.sql_store_spec$fn__3397 invoke "sql_store_spec.clj" 15]
  [clojure.test$test_var$fn__7670 invoke "test.clj" 704]
  [clojure.test$test_var invoke "test.clj" 704]
  [clojure.test$test_vars$fn__7692$fn__7697 invoke "test.clj" 722]
  [clojure.test$default_fixture invoke "test.clj" 674]
  [clojure.test$test_vars$fn__7692 invoke "test.clj" 722]
  [ctia.test_helpers.core$fixture_allow_all_auth invoke "core.clj" 165]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [ctia.test_helpers.db$fixture_db_recreate_tables invoke "db.clj" 67]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [ctia.test_helpers.core$fixture_ctia$fn__7088 invoke "core.clj" 147]
  [ctia.test_helpers.core$with_properties_ invoke "core.clj" 57]
  [ctia.test_helpers.core$fixture_ctia invoke "core.clj" 141]
  [ctia.test_helpers.core$fixture_ctia invoke "core.clj" 134]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [ctia.test_helpers.db$fixture_properties_COLON_sql_store$fn__3386 invoke "db.clj" 62]
  [ctia.test_helpers.core$with_properties_ invoke "core.clj" 57]
  [ctia.test_helpers.db$fixture_properties_COLON_sql_store invoke "db.clj" 46]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [ctia.test_helpers.core$fixture_properties_COLON_clean$fn__2155 invoke "core.clj" 85]
  [ctia.test_helpers.core$with_properties_ invoke "core.clj" 57]
  [ctia.test_helpers.core$fixture_properties_COLON_clean invoke "core.clj" 72]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [ctia.test_helpers.core$fixture_schema_validation$fn2182__2191$fn__2192 invoke "core.clj" 159]
  [ctia.test_helpers.core$fixture_schema_validation$fn2182__2191 invoke "core.clj" 158]
  [clojure.lang.AFn applyToHelper "AFn.java" 152]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 29]
  [clojure.lang.RestFn invoke "RestFn.java" 397]
  [ctia.test_helpers.core$fixture_schema_validation invoke "core.clj" 158]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [clojure.test$default_fixture invoke "test.clj" 674]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [clojure.test$default_fixture invoke "test.clj" 674]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$test_vars invoke "test.clj" 718]
  [clojure.test$test_all_vars invoke "test.clj" 728]
  [clojure.test$test_ns invoke "test.clj" 747]
  [clojure.core$map$fn__4553 invoke "core.clj" 2624]
  [clojure.lang.LazySeq sval "LazySeq.java" 40]
  [clojure.lang.LazySeq seq "LazySeq.java" 49]
  [clojure.lang.Cons next "Cons.java" 39]
  [clojure.lang.RT next "RT.java" 674]
  [clojure.core$next__4112 invoke "core.clj" 64]
  [clojure.core$reduce1 invoke "core.clj" 909]
  [clojure.core$reduce1 invoke "core.clj" 900]
  [clojure.core$merge_with doInvoke "core.clj" 2936]
  [clojure.lang.RestFn applyTo "RestFn.java" 139]
  [clojure.core$apply invoke "core.clj" 632]
  [clojure.test$run_tests doInvoke "test.clj" 762]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invoke "core.clj" 630]
  [user$eval85$fn__146$fn__179 invoke "form-init2230180263327805707.clj" 1]
  [user$eval85$fn__146$fn__147 invoke "form-init2230180263327805707.clj" 1]
  [user$eval85$fn__146 invoke "form-init2230180263327805707.clj" 1]
  [user$eval85 invoke "form-init2230180263327805707.clj" 1]
  [clojure.lang.Compiler eval "Compiler.java" 6782]
  [clojure.lang.Compiler eval "Compiler.java" 6772]
  [clojure.lang.Compiler load "Compiler.java" 7227]
  [clojure.lang.Compiler loadFile "Compiler.java" 7165]
  [clojure.main$load_script invoke "main.clj" 275]
  [clojure.main$init_opt invoke "main.clj" 280]
  [clojure.main$initialize invoke "main.clj" 308]
  [clojure.main$null_opt invoke "main.clj" 343]
  [clojure.main$main doInvoke "main.clj" 421]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [clojure.lang.Var invoke "Var.java" 383]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.Var applyTo "Var.java" 700]
  [clojure.main main "main.java" 37]]}, :seed 1464363559791, :failing-size 28, :num-tests 29, :fail [{:observable {:value "Y}YUokb", :type "imsi"}, :source "av", :id "judgement-}", :priority -1, :severity -86, :confidence "Low", :valid_time {:start_time "2016-07-29T15:39:21.085Z"}}], :shrunk {:total-nodes-visited 18, :depth 4, :result #error {
 :cause "Assert failed: Assert Failed: null of type null must be a string\n(string? s)"
 :via
 [{:type java.lang.AssertionError
   :message "Assert failed: Assert Failed: null of type null must be a string\n(string? s)"
   :at [ctia.test_helpers.core$encode invoke "core.clj" 289]}]
 :trace
 [[ctia.test_helpers.core$encode invoke "core.clj" 289]
  [ctia.http.generative.specs$fn__3322 invoke "specs.clj" 86]
  [clojure.lang.AFn applyToHelper "AFn.java" 154]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invoke "core.clj" 630]
  [clojure.test.check.properties$apply_gen$fn__1761$fn__1762 invoke "properties.cljc" 16]
  [clojure.test.check.properties$apply_gen$fn__1761 invoke "properties.cljc" 16]
  [clojure.test.check.rose_tree$fmap invoke "rose_tree.cljc" 78]
  [clojure.test.check.rose_tree$fmap$fn__379 invoke "rose_tree.cljc" 78]
  [clojure.core$map$fn__4553 invoke "core.clj" 2624]
  [clojure.lang.LazySeq sval "LazySeq.java" 40]
  [clojure.lang.LazySeq seq "LazySeq.java" 49]
  [clojure.lang.RT seq "RT.java" 507]
  [clojure.core$seq__4128 invoke "core.clj" 137]
  [clojure.test.check$shrink_loop invoke "check.cljc" 108]
  [clojure.test.check$failure invoke "check.cljc" 125]
  [clojure.test.check$quick_check doInvoke "check.cljc" 70]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invoke "core.clj" 634]
  [ctia.http.generative.sql_store_spec$spec_judgement_routes_sql_store doInvoke "sql_store_spec.clj" 15]
  [clojure.lang.RestFn applyTo "RestFn.java" 139]
  [clojure.core$apply invoke "core.clj" 632]
  [ctia.http.generative.sql_store_spec$spec_judgement_routes_sql_store invoke "sql_store_spec.clj" 15]
  [ctia.http.generative.sql_store_spec$fn__3397 invoke "sql_store_spec.clj" 15]
  [clojure.test$test_var$fn__7670 invoke "test.clj" 704]
  [clojure.test$test_var invoke "test.clj" 704]
  [clojure.test$test_vars$fn__7692$fn__7697 invoke "test.clj" 722]
  [clojure.test$default_fixture invoke "test.clj" 674]
  [clojure.test$test_vars$fn__7692 invoke "test.clj" 722]
  [ctia.test_helpers.core$fixture_allow_all_auth invoke "core.clj" 165]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [ctia.test_helpers.db$fixture_db_recreate_tables invoke "db.clj" 67]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [ctia.test_helpers.core$fixture_ctia$fn__7088 invoke "core.clj" 147]
  [ctia.test_helpers.core$with_properties_ invoke "core.clj" 57]
  [ctia.test_helpers.core$fixture_ctia invoke "core.clj" 141]
  [ctia.test_helpers.core$fixture_ctia invoke "core.clj" 134]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [ctia.test_helpers.db$fixture_properties_COLON_sql_store$fn__3386 invoke "db.clj" 62]
  [ctia.test_helpers.core$with_properties_ invoke "core.clj" 57]
  [ctia.test_helpers.db$fixture_properties_COLON_sql_store invoke "db.clj" 46]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [ctia.test_helpers.core$fixture_properties_COLON_clean$fn__2155 invoke "core.clj" 85]
  [ctia.test_helpers.core$with_properties_ invoke "core.clj" 57]
  [ctia.test_helpers.core$fixture_properties_COLON_clean invoke "core.clj" 72]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [ctia.test_helpers.core$fixture_schema_validation$fn2182__2191$fn__2192 invoke "core.clj" 159]
  [ctia.test_helpers.core$fixture_schema_validation$fn2182__2191 invoke "core.clj" 158]
  [clojure.lang.AFn applyToHelper "AFn.java" 152]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 29]
  [clojure.lang.RestFn invoke "RestFn.java" 397]
  [ctia.test_helpers.core$fixture_schema_validation invoke "core.clj" 158]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [clojure.test$default_fixture invoke "test.clj" 674]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$compose_fixtures$fn__7664$fn__7665 invoke "test.clj" 681]
  [clojure.test$default_fixture invoke "test.clj" 674]
  [clojure.test$compose_fixtures$fn__7664 invoke "test.clj" 681]
  [clojure.test$test_vars invoke "test.clj" 718]
  [clojure.test$test_all_vars invoke "test.clj" 728]
  [clojure.test$test_ns invoke "test.clj" 747]
  [clojure.core$map$fn__4553 invoke "core.clj" 2624]
  [clojure.lang.LazySeq sval "LazySeq.java" 40]
  [clojure.lang.LazySeq seq "LazySeq.java" 49]
  [clojure.lang.Cons next "Cons.java" 39]
  [clojure.lang.RT next "RT.java" 674]
  [clojure.core$next__4112 invoke "core.clj" 64]
  [clojure.core$reduce1 invoke "core.clj" 909]
  [clojure.core$reduce1 invoke "core.clj" 900]
  [clojure.core$merge_with doInvoke "core.clj" 2936]
  [clojure.lang.RestFn applyTo "RestFn.java" 139]
  [clojure.core$apply invoke "core.clj" 632]
  [clojure.test$run_tests doInvoke "test.clj" 762]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invoke "core.clj" 630]
  [user$eval85$fn__146$fn__179 invoke "form-init2230180263327805707.clj" 1]
  [user$eval85$fn__146$fn__147 invoke "form-init2230180263327805707.clj" 1]
  [user$eval85$fn__146 invoke "form-init2230180263327805707.clj" 1]
  [user$eval85 invoke "form-init2230180263327805707.clj" 1]
  [clojure.lang.Compiler eval "Compiler.java" 6782]
  [clojure.lang.Compiler eval "Compiler.java" 6772]
  [clojure.lang.Compiler load "Compiler.java" 7227]
  [clojure.lang.Compiler loadFile "Compiler.java" 7165]
  [clojure.main$load_script invoke "main.clj" 275]
  [clojure.main$init_opt invoke "main.clj" 280]
  [clojure.main$initialize invoke "main.clj" 308]
  [clojure.main$null_opt invoke "main.clj" 343]
  [clojure.main$main doInvoke "main.clj" 421]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [clojure.lang.Var invoke "Var.java" 383]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.Var applyTo "Var.java" 700]
  [clojure.main main "main.java" 37]]}, :smallest [{:observable {:value "greWK_<`O", :type "pki-serial"}, :source ",?s", :id "judgement-0", :priority -3, :severity -2, :confidence "None", :valid_time {:start_time "2016-05-27T15:39:21.374Z"}}]}, :test-var "spec-judgement-routes-sql-store"}
```

References:
https://travis-ci.org/threatgrid/ctia/jobs/133412606
https://github.com/threatgrid/ctia/pull/322/commits/76516fc873cc6a1b7550ae596c3cc5014f7fa9e1

**Comment by polygloton** [comment] 2016-05-27 16:06
Hopefully this problem will go way with #311

**Comment by polygloton** [comment] 2016-07-11 16:50
Haven't seen this error in a while.  I am assuming that it is resolved by changes to our ID format.

**Comment by gbuisson** [comment] 2016-07-11 16:58
This happens on generative tests, the workflow is to `POST`, `GET` the `id` of the response of the `POST` and initiate a `GET` on this `id`.

since all this workflow is chained and destructured on a let form, if the `POST` fails (for example if the schema or es mapping is incorrect), the id is then `nil` and `encode` throws.

we might want to remove the destructuring on the let and add an assertion on the `id`

**Closed** 2016-12-08 04:57 UTC
Labels: bug
